# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vega multi view
email: daniel@abumarkub.net
description: >- # this means to ignore newlines until "baseurl:"
    Vega multi view (vmv) is a wrapper of the Vega runtime API that
    allows you to add multiple Vega views to a HTML page that can
    listen to each other's signals and share datasets or manipulations
    thereof, despite the fact that each view lives in a separate HTML element.
baseurl: "/vega-multi-view" # the subpath of your site, e.g. /blog
url: "https://abudaan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  abudaan

# Build settings
markdown: kramdown
highlighter: rouge
theme: slate
plugins:
  - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_id_stripping: true

exclude:
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass
    # style: :compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
